---

- name: upgrade all packages, excluding kernel & foo related packages
  yum:
    name: '*'
    state: latest

- name: Ensure a list of yum packages are installed
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
    - python-pip
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - amazon-linux-extras
    - git

- name: Add extras repository
  shell: yum-config-manager --enable extras

- name: Install docker-ce (centos) via amazon-linux-extras packages
  shell: "amazon-linux-extras install docker=18.06.1 -y"

- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: yes

- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: Install Docker Compose (if configured).
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755

- name: Ensure Python pip packages are installed
  pip:
    name: "{{ packages }}"
  vars:
    packages:
    - boto
    - boto3