---
- name: created lumis www directory
  file:
    path: "{{ item }}"
    mode: 0777
    state: directory
  with_items:
    - /data/lumisxp_data01
    - /data/lumisxp_data02
    - /data/lumisxp_data03
    - /data/es_analysis
    - /data/htdocs
    - /data/lumis_shared

- name: Create symbolic link 
  file:
   src: "/data/{{ item }}/"
   dest: "/var/lib/docker/volumes/{{ item }}"
   state: link
  with_items:
    - lumisxp_data01
    - lumisxp_data02
    - lumisxp_data03
    - es_analysis
    - htdocs
    - lumis_shared

- name: creating source directory"
  file:
    path: "~/lumisxp-docker-swarm"
    state: directory    
    recurse: yes
  become: yes

- file:
    path: "~/lumisxp-docker-swarm"
    mode: 0777
    state: directory
  become: yes

- name: cloning repo
  git:
    repo: "https://github.com/jeduoliveira/lumisxp-docker-swarm"
    version: "master"
    dest: "~/lumisxp-docker-swarm"
    accept_hostkey: yes
    force: yes

- name: cloning repo
  shell: "cd ~/lumisxp-docker-swarm && make pull"
