---
- name: Start Config
  hosts: all
  gather_facts: True
  become: True
  vars:
    nfs_exports: "*(rw,sync,no_root_squash,no_all_squash)"
  roles:
    - { role: common }
    - { role: geerlingguy.docker }

- name: NFS Server
  hosts: manager1
  gather_facts: True
  become: True
  
  roles:
    - { role: nfs-server }
    
- name: NSF Client
  hosts: nfsclients
  gather_facts: False
  become: True
  vars:
    server_master_ip: 192.168.50.10
    docker_swarm_manager_ip: 192.168.50.10
    docker_swarm_manager_port: 2377
  roles:
    - { role: nfs-client }
    
- name: Swarm Managers
  hosts: docker_swarm_manager
  gather_facts: True
  become: True
  vars:
    docker_swarm_manager_ip: 192.168.50.10
    docker_swarm_manager_port: 2377
  roles:
    - { role: manager }

- name: Swarm Workers
  hosts: workers
  gather_facts: False
  become: True
  vars:
    docker_swarm_manager_ip: 192.168.50.10
    docker_swarm_manager_port: 2377
  roles:
    - { role: worker }
  
- name: Initial Config
  hosts: all
  gather_facts: True
  become: True
  roles:
    - { role: initial }
    