---
- name: Configurando Global
  hosts: all
  gather_facts: True
  become: True
  vars:
    nfs_exports: "*(rw,sync,no_root_squash,no_all_squash)"
  #  efs_path: "fs-da3556a2.efs.us-east-2.amazonaws.com"
  roles:
    - { role: common }
    - { role: geerlingguy.docker }


- name: NSF Server
  hosts: manager
  gather_facts: False
  become: True
  roles:
    - { role: nfs-server }

- name: NSF Client
  hosts: workers
  gather_facts: False
  become: True
  vars:
    server_master_ip: 192.168.50.10
  roles:
    - { role: nfs-client }
    