---
- name: Configurando Global
  hosts: all
  gather_facts: True
  become: True
  vars:
    nfs_exports: "*(rw,sync,no_root_squash,no_all_squash)"
  roles:
    - { role: common }
    - { role: geerlingguy.docker }

- name: NSF Server
  hosts: manager
  gather_facts: True
  become: True
  vars:
    docker_swarm_manager_ip: 192.168.50.10
    docker_swarm_manager_port: 2377
  roles:
    - { role: nfs-server }
    - { role: manager }

- name: NSF Client
  hosts: workers
  gather_facts: False
  become: True
  vars:
    server_master_ip: 192.168.50.10
    docker_swarm_manager_ip: 192.168.50.10
    docker_swarm_manager_port: 2377
  roles:
    - { role: nfs-client }
    - { role: worker }
  
- name: Configurando Global
  hosts: all
  gather_facts: True
  become: True
  roles:
    - { role: initial }
    