---

- name: Ensure NFS is installed.
  package: 
    name: nfs-utils 
    state: installed

- name: Ensure mount directory exists.
  file:
    path: "/data"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Ensure EFS volume is mounted.
  mount:
    name: /data
    src: "{{ efs_path }}:/"
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
    state: mounted

- name: Ensure mount directory exists.
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items:
    - /data/elasticsearch/data01
    - /data/elasticsearch/data02
    - /data/elasticsearch/data03
    - /data/elasticsearch/config/lumis-analysis


  


